apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-namenode-deployment
  labels:
    app: hdfs-namenode
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hdfs-namenode
  template:
    metadata:
      labels:
        app: hdfs-namenode
    spec:
      containers:
      - name: hdfs-namenode-container
        image: <HDFS Namenode image here (https://hub.docker.com/r/bde2020/hadoop-namenode)>
        ports:
        - containerPort: 9000
        - containerPort: 9870
        - containerPort: 50070
        env:
        - name: CLUSTER_NAME
          value: "cs1660-project-op1"
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode-local-service:9000"
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: "root"
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: "*"
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: "*"
        - name: CORE_CONF_io_compression_codecs
          value: "org.apache.hadoop.io.compress.SnappyCodec"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hdfs-datanode-deployment
  labels:
    app: hdfs-datanode
spec:
  replicas: 0
  selector:
    matchLabels:
      app: hdfs-datanode
  template:
    metadata:
      labels:
        app: hdfs-datanode
    spec:
      containers:
      - name: hdfs-datanode-container
        image: <HDFS Datanode image here (https://hub.docker.com/r/bde2020/hadoop-datanode)>
        ports:
        - containerPort: 9867
        - containerPort: 9866
        - containerPort: 9864
        env:
        - name: CORE_CONF_fs_defaultFS
          value: "hdfs://namenode-local-service:9000"
        - name: CORE_CONF_hadoop_http_staticuser_user
          value: "root"
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          value: "*"
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          value: "*"
        - name: CORE_CONF_io_compression_codecs
          value: "org.apache.hadoop.io.compress.SnappyCodec"
        - name: HDFS_CONF_dfs_webhdfs_enabled
          value: "true"
        - name: HDFS_CONF_dfs_permissions_enabled
          value: "false"
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          value: "false"
        - name: SERVICE_PRECONDITION
          value: "namenode-local-service:9000"
---
apiVersion: v1
kind: Service
metadata:
  name: namenode-local-service
spec:
  selector:
    app: hdfs-namenode
  ports:
  - port: 9870
    targetPort: 9870
    name: namenode9870
  - port: 9000
    targetPort: 9000
    name: namenode9000
---
apiVersion: v1
kind: Service
metadata:
  name: namenode-public-service
spec:
  type: NodePort
  selector:
    app: hdfs-namenode
  ports:
  - port: 9870
    targetPort: 9870
    nodePort: 30006
