apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonar-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar-container
        image: <SonarQube and SonarScanner image here (https://hub.docker.com/r/jfrank206/sonarqube-sonarscanner)>
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: sonar-service
spec:
  type: NodePort
  selector:
    app: sonar
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 30004