apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark-container
        image: gcr.io/fair-solution-326122/bitnami/spark:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-service
spec:
  type: NodePort
  selector:
    app: spark
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002