apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deployment
spec:
  replicas: 0
  selector:
    matchLabels:
      app: jupyter-notebook
  template:
    metadata:
      labels:
        app: jupyter-notebook
    spec:
      containers:
      - name: notebook-container
        image: <Jupyter Notebook image here (https://hub.docker.com/r/jfrank206/notebook-open)>
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: notebook-service
spec:
  type: NodePort
  selector:
    app: jupyter-notebook
  ports:
  - port: 8888
    targetPort: 8888
    nodePort: 30003