apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-driver-deployment
  labels:
    app: flask-driver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-driver
  template:
    metadata:
      labels:
        app: flask-driver
    spec:
      containers:
      - name: flask-driver-web
        image: gcr.io/fair-solution-326122/jfrank206/project1-driver:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-driver-service
spec:
  type: NodePort
  selector:
    app: flask-driver
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001


